package de.lukeslog.alarmclock.ambientalarm;

import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.WindowManager;

import org.joda.time.DateTime;

import java.util.ArrayList;

import de.lukeslog.alarmclock.datatabse.AmbientAlarmDatabase;
import de.lukeslog.alarmclock.main.ClockWorkService;
import de.lukeslog.alarmclock.main.NotificationManagement;
import de.lukeslog.alarmclock.startup.NotificationService;
import de.lukeslog.alarmclock.support.AlarmClockConstants;

/**
 * Created by lukas on 31.03.14.
 *
 * Manages the set of alarms generated by the user, also manages access to the database.
 */
public class AmbientAlarmManager
{

    private static ArrayList<AmbientAlarm> registeredAlarms;

    public static final String PREFS_NAME = AlarmClockConstants.PREFS_NAME;
    public static String TAG = AlarmClockConstants.TAG;

    /**
     *
     * This method informs all currently active alarms of the current time, this time may then
     * be transformed into actions by these alarms
     *
     * @param currentTime to inform all alerts of an identical time the current Time is provided by
     *                    the calling method
     */
    public static void notifyActiveAlerts(DateTime currentTime)
    {
        if(registeredAlarms!=null)
        {
            //Log.d(TAG, "--tick--" + registeredAlarms.size());
            for (AmbientAlarm alarm : registeredAlarms)
            {
                if (alarm.isActive())
                {
                    alarm.notifyOfCurrentTime(currentTime);
                }
            }
        }
        else
        {
            updateListFromDataBase();
        }
    }

    /**
     * add a new ambient alarm to the registry
     *
     * @param ambientAlarm
     */
    public static void addNewAmbientAlarm(AmbientAlarm ambientAlarm)
    {
        Log.d(TAG, "  addNewAmbientAlarm(AmbientAlarm)");
        if(registeredAlarms!=null)
        {
            registeredAlarms.add(ambientAlarm);
        }
        else
        {
            updateListFromDataBase();
            registeredAlarms.add(ambientAlarm);
        }
        AmbientAlarmDatabase.updateAmbientAlarm(ambientAlarm);
    }

    public static void updateDataBaseEntry(AmbientAlarm ambientAlarm)
    {
        Log.d(TAG, "  updateDatabaseEntry(AmbientAlarm)");
        AmbientAlarmDatabase.updateAmbientAlarm(ambientAlarm);
    }

    public static ArrayList<AmbientAlarm> getListOfAmbientAlarms()
    {
        Log.d(TAG, "  getListOfAmbientAlarms()");
        return registeredAlarms;
    }

    public static void updateListFromDataBase()
    {
        Log.d(TAG, "  update Alarm List from Database");
        //Log.d(TAG, "  Listsize="+registeredAlarms.size());
        registeredAlarms = AmbientAlarmDatabase.getAllAlarmsFromDatabase();
        Log.d(TAG, "  Listsize="+registeredAlarms.size());
    }

    public static void startAlarmActivity(AmbientAlarm ambientAlarm)
    {
        Log.d(TAG, "  startAlarmActivity!");
        Context ctx = NotificationService.getContext();
        if(ctx!=null)
        {
            Log.d(TAG, "  ctx is not null");
            String alarmID = ambientAlarm.getAlarmID();
            Log.d(TAG, "  alarmid is "+alarmID);
            Intent intent = new Intent(ctx, ambientAlarm.getAlarmActivity());
            Log.d(TAG, "  Intent created....");
           // intent.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED | WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD | WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON | WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);
            Log.d(TAG, "  strage stuff...");
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
            Log.d(TAG, "  now start stuff....");
            intent.putExtra("ambientAlarmID", alarmID);
            ctx.startActivity(intent);
        }
        else
        {
            Log.e(TAG, "CONTEXT WAS NULL!!!!! ALARMACTIVITY COULD NOT BE STARTED!");
        }
    }

    public static void deleteAmbientAlarm(int position)
    {
        Log.d(TAG, "  delete Ambient Alarm!");
        if(registeredAlarms!=null)
        {
            AmbientAlarmDatabase.removeAmbientAlarm(registeredAlarms.get(position));
            registeredAlarms.remove(position);
        }
    }

    public static AmbientAlarm getAlarmById(String alarmID)
    {
        if(registeredAlarms!=null)
        {
            Log.d(TAG, "  getAlarmByID " + alarmID);
            Log.d(TAG, "  size of AlarmList " + registeredAlarms.size());
            for (AmbientAlarm alarm : registeredAlarms)
            {
                Log.d(TAG, "    -->" + alarm.getAlarmID());
                if (alarm.getAlarmID().equals(alarmID))
                {
                    return alarm;
                }
            }
            return null;
        }
        else
        {
            updateListFromDataBase();
            return getAlarmById(alarmID);
        }
    }
}
